In [1]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\Lenovo\PycharmProjects\EnergyEfficiency\Dataset\Scaling.csv")
df.head()

,Unnamed: 0,relative compactness,surface area,wall area,roof area,overall height,orientation,glazing area,glazing area distribution,heating load,cooling load
0,0,0.98,514.5,294.0,110.25,7.0,2,0.0,0,15.55,21.33
1,1,0.98,514.5,294.0,110.25,7.0,3,0.0,0,15.55,21.33
2,2,0.98,514.5,294.0,110.25,7.0,4,0.0,0,15.55,21.33
3,3,0.98,514.5,294.0,110.25,7.0,5,0.0,0,15.55,21.33
4,4,0.90,563.5,318.5,122.50,7.0,2,0.0,0,20.84,28.28

In [3]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [4]:
df.head()

,relative compactness,surface area,wall area,roof area,overall height,orientation,glazing area,glazing area distribution,heating load,cooling load
0,0.98,514.5,294.0,110.25,7.0,2,0.0,0,15.55,21.33
1,0.98,514.5,294.0,110.25,7.0,3,0.0,0,15.55,21.33
2,0.98,514.5,294.0,110.25,7.0,4,0.0,0,15.55,21.33
3,0.98,514.5,294.0,110.25,7.0,5,0.0,0,15.55,21.33
4,0.90,563.5,318.5,122.50,7.0,2,0.0,0,20.84,28.28

In [5]:
scaling_feature =[feature for feature in df.columns if feature not in ['cooling load','heating load']]
df[scaling_feature].head()

,relative compactness,surface area,wall area,roof area,overall height,orientation,glazing area,glazing area distribution
0,0.98,514.5,294.0,110.25,7.0,2,0.0,0
1,0.98,514.5,294.0,110.25,7.0,3,0.0,0
2,0.98,514.5,294.0,110.25,7.0,4,0.0,0
3,0.98,514.5,294.0,110.25,7.0,5,0.0,0
4,0.90,563.5,318.5,122.50,7.0,2,0.0,0

In [6]:
scaler = MinMaxScaler()
data = scaler.fit_transform(df[scaling_feature])
data

array([[1.        , 0.        , 0.28571429, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.28571429, ..., 0.33333333, 0.        ,
        0.        ],
       [1.        , 0.        , 0.28571429, ..., 0.66666667, 0.        ,
        0.        ],
       ...,
       [0.        , 1.        , 0.71428571, ..., 0.33333333, 1.        ,
        1.        ],
       [0.        , 1.        , 0.71428571, ..., 0.66666667, 1.        ,
        1.        ],
       [0.        , 1.        , 0.71428571, ..., 1.        , 1.        ,
        1.        ]])

In [7]:
data.shape

(768, 8)

In [8]:
VIF = pd.DataFrame()
VIF['vif'] = [variance_inflation_factor (data,i) for i in range(data.shape[1])]
VIF['feature'] = df[scaling_feature].columns
VIF

            vif                    feature
0    105.524054       relative compactness
1  31190.507641               surface area
2   5459.755056                  wall area
3  17319.814328                  roof area
4     31.205474             overall height
5      1.000000                orientation
6      1.047508               glazing area
7      1.047508  glazing area distribution

**As we see that from VIF the value will be beyond 10. So we decide to perform an analysis designed for highly correlated variables, such as Principal Components Analysis**

In [9]:
pca=PCA()
data2=pca.fit_transform(data)
data2

array([[ 1.06199953e+00, -5.00000000e-01,  8.04194062e-01, ...,
         1.87998678e-01, -1.94322702e-02,  2.91999582e-15],
       [ 1.06199953e+00, -1.66666667e-01,  8.04194062e-01, ...,
         1.87998678e-01, -1.94322702e-02, -9.75184846e-17],
       [ 1.06199953e+00,  1.66666667e-01,  8.04194062e-01, ...,
         1.87998678e-01, -1.94322702e-02, -9.00402463e-17],
       ...,
       [-8.45733471e-01, -1.66666667e-01, -5.91673381e-01, ...,
         4.46380243e-02, -3.77684211e-02, -7.21308046e-17],
       [-8.45733471e-01,  1.66666667e-01, -5.91673381e-01, ...,
         4.46380243e-02, -3.77684211e-02, -6.73364485e-17],
       [-8.45733471e-01,  5.00000000e-01, -5.91673381e-01, ...,
         4.46380243e-02, -3.77684211e-02, -6.25420924e-17]])

In [10]:
data2.shape

(768, 8)

In [11]:
VIF = pd.DataFrame()
VIF['vif'] = [variance_inflation_factor (data2,i) for i in range(data2.shape[1])]
VIF['feature'] = df[scaling_feature].columns
VIF

   vif                    feature
0  1.0       relative compactness
1  1.0               surface area
2  1.0                  wall area
3  1.0                  roof area
4  1.0             overall height
5  1.0                orientation
6  1.0               glazing area
7  1.0  glazing area distribution

In [12]:
one = df[['heating load','cooling load']]

In [13]:
two = pd.DataFrame(data2,columns=df[scaling_feature].columns)

In [14]:
df_new = pd.concat([one,two],axis=1)
df_new.head()

,heating load,cooling load,relative compactness,surface area,wall area,roof area,overall height,orientation,glazing area,glazing area distribution
0,15.55,21.33,1.062000,-0.500000,0.804194,-0.338293,-0.114022,0.187999,-0.019432,2.919996e-15
1,15.55,21.33,1.062000,-0.166667,0.804194,-0.338293,-0.114022,0.187999,-0.019432,-9.751848e-17
2,15.55,21.33,1.062000,0.166667,0.804194,-0.338293,-0.114022,0.187999,-0.019432,-9.004025e-17
3,15.55,21.33,1.062000,0.500000,0.804194,-0.338293,-0.114022,0.187999,-0.019432,-1.349037e-16
4,20.84,28.28,0.868368,-0.500000,0.804194,-0.095116,-0.114022,0.074478,0.000547,5.217437e-17

In [15]:
#df_new.to_csv(r'C:\Users\Lenovo\PycharmProjects\EnergyEfficiency\Dataset\Model_Building.csv')

In [16]:
import pickle
file = 'Energy_Efficiency_pca.pkl'

pickle.dump(pca, open(file,'wb'))